schema_version = "1.0.0"

id = "node_preset_manager"
version = "1.0.0"
name = "曼波工具箱 - 节点预设管理"
tagline = "mambo_toolbox_node_preset"
description = "曼波工具箱系列插件之一，提供节点预设保存与加载功能"
maintainer = "JuziD"
type = "add-on"

blender_version_min = "3.2.0"
location = "节点编辑器 > 侧边栏"
category = "Node"



license = ["SPDX:GPL-3.0-or-later"]
